### ISSUE TITLE
Cronjobs? 

### ISSUE THREAD

**Issue by CT83** [guysoft/HotSpotOS#1] opened 2018-07-14 16:58 UTC
Are CronJobs added with the Image? I have installed it and I don't think the timer is working, the RPi does not create a Hotspot after 5 minutes.

**Comment by guysoft** [comment] 2018-07-14 16:59
Should be, 
Check running ``crontab -l`` as root.

What image are you using?

**Comment by CT83** [comment] 2018-07-15 01:33
I am using [HostSpotOS 0.1.0 Stretch Lite](http://unofficialpi.org/Distros/HostSpotOS/2018-06-26_2018-04-18-hostspotos-stretch-lite-0.1.0.zip)
Okay, I fixed it the problem was that the CronJobs were not running. 
I used `sudo grep /usr/bin/autohotspotN /var/log/syslog` to check Cron logs, turns out, jobs were running fine until 6 hours ago. After some digging I figured that the problem was that the CronJobs were not running, due to them not being run as `root` or them not being run at all. I followed this [stackoverflow answer](https://stackoverflow.com/a/45540857/7127317), and added the jobs to System-Wide CronTab. Everything seems to be working now.
I have few more doubts and issues, I will open them individually to make it easy for you to reference them in a PR

**Comment by guysoft** [comment] 2018-07-25 10:55
Thanks! Awaiting PR :)

**Comment by CT83** [comment] 2018-07-25 16:27
I will try to make a PR, but if I don't could you please verify if you are facing this issue too? Or is it just me? Maybe changing the root password triggered it? 🤷

**Comment by guysoft** [comment] 2018-07-25 16:32
The issue is that it works for me here. So I have no way to test beyond.
The thing is, if a PR makes it work for both me and you. then its worth pulling. There might be other users it fixes issues for them.

**Comment by guysoft** [comment] 2018-09-27 09:12
Closing if no reply

**Closed as completed** 2020-01-29 14:08 UTC
